FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    snort \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/snort

COPY snort.conf /etc/snort/snort.conf
COPY rules/local.rules /etc/snort/rules/local.rules

# Gunakan br-7952696ba20b untuk monitor traffic antar container
CMD ["snort", "-i", "ens33", "-c", "/etc/snort/snort.conf", "-A", "fast", "-l", "/var/log/snort"]
