services:

  # ========================
  # Container 1: Web Server + Database
  # ========================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesbuk-app_101032330051
    volumes:
      - pesbuk_data:/app/data
    networks:
      - pesbuk-network

  # ========================
  # Container 2: Snort IDS
  # Pakai network_mode: host agar bisa monitor bridge pesbuk-br dari sisi host
  # ========================
  snort:
    build:
      context: ./snort
      dockerfile: Dockerfile.snort
    container_name: pesbuk-snort_101032330051
    network_mode: host          # akses langsung ke interface host (termasuk pesbuk-br)
    cap_add:
      - NET_ADMIN               # izin monitor jaringan
      - NET_RAW                 # izin baca raw packet
    volumes:
      - ./snort/logs:/var/log/snort   # log alert tersimpan di host
    depends_on:
      - app
      - nginx

  # ========================
  # Container 3: Nginx (HTTPS + reverse proxy)
  # ========================
  nginx:
    image: nginx:alpine
    container_name: pesbuk-nginx_101032330051
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/ssl/cert.pem
      - ./ssl/key.pem:/etc/ssl/key.pem
    depends_on:
      - app
    networks:
      - pesbuk-network

  # ========================
  # Container 4: User / Attacker
  # Ubuntu dengan tools serangan: curl, hydra, sqlmap, nmap
  # Cara pakai: docker exec -it pesbuk-user_101032330051 bash
  # ========================
  user:
    build:
      context: ./user
      dockerfile: Dockerfile.user
    container_name: pesbuk-user_101032330051
    networks:
      - pesbuk-network
    stdin_open: true
    tty: true
    cap_add:
      - NET_RAW               # izin kirim raw packet (dibutuhkan nmap SYN/XMAS/NULL/FIN scan)

networks:
  pesbuk-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pesbuk-br   # nama bridge TETAP agar Snort bisa monitor

volumes:
  pesbuk_data:
