FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    hydra \
    sqlmap \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Tetap jalan (agar bisa docker exec)
CMD ["tail", "-f", "/dev/null"]
